# Generated by Django 6.0 on 2026-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_uimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
